/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Config = IDL.Record({
  'alertsEnabled' : IDL.Bool,
  'alertThreshold' : IDL.Float64,
  'apiEndpoint' : IDL.Text,
  'deviceName' : IDL.Text,
  'location' : IDL.Text,
});
export const Reading = IDL.Record({
  'status' : IDL.Text,
  'level' : IDL.Float64,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addReading' : IDL.Func([IDL.Float64, IDL.Text], [], []),
  'fetchWaterLevel' : IDL.Func([IDL.Text], [IDL.Float64], []),
  'getConfig' : IDL.Func([], [Config], ['query']),
  'getReadings' : IDL.Func([], [IDL.Vec(Reading)], ['query']),
  'updateConfig' : IDL.Func([Config], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Config = IDL.Record({
    'alertsEnabled' : IDL.Bool,
    'alertThreshold' : IDL.Float64,
    'apiEndpoint' : IDL.Text,
    'deviceName' : IDL.Text,
    'location' : IDL.Text,
  });
  const Reading = IDL.Record({
    'status' : IDL.Text,
    'level' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addReading' : IDL.Func([IDL.Float64, IDL.Text], [], []),
    'fetchWaterLevel' : IDL.Func([IDL.Text], [IDL.Float64], []),
    'getConfig' : IDL.Func([], [Config], ['query']),
    'getReadings' : IDL.Func([], [IDL.Vec(Reading)], ['query']),
    'updateConfig' : IDL.Func([Config], [], []),
  });
};

export const init = ({ IDL }) => { return []; };